// Coffee knowledge hints — shown while Claude generates your brew recipe
// ~300 hints covering origins, processing, brewing science, equipment, history,
// variety science, fermentation, roast chemistry, championships, and more

export const COFFEE_HINTS: string[] = [
  // Origins & terroir
  "Ethiopia is considered the birthplace of coffee — wild coffee plants still grow in the Kaffa forest.",
  "Yirgacheffe's altitude of 1,700–2,200 m creates the slow cherry ripening that builds its famous floral notes.",
  "Kenyan AA grade refers to bean screen size (18+), not quality — but high altitude tends to correlate with both.",
  "Gesha variety was discovered in the Gesha forest of Ethiopia and brought to Panama, where it became legendary.",
  "Brazil is the world's largest coffee producer, but its flat terrain means most coffee is dried naturally.",
  "Colombia's geography — two Andes ranges — creates micro-climates that allow harvesting nearly year-round.",
  "Sumatra's 'wet-hulled' Giling Basah process creates the distinctive earthy, low-acid profile of Mandheling coffees.",
  "Rwanda's volcanic Lake Kivu soils produce coffees with a distinctive winey complexity.",
  "Burundi and Rwanda share nearly identical altitude and terroir — tiny regional variations define their character.",
  "Yemen's ancient mocha port gave espresso its first name — 'mocha' referred to the coffee, not the drink.",
  "Costa Rican 'honey' processing was pioneered partly because water for washed processing is scarce in dry season.",
  "Panama's Boquete region benefits from cold 'Bajareque' mist that slows ripening, concentrating sugars.",
  "Guatemala's Antigua coffees come from volcanic soil enriched by three nearby volcanoes.",
  "Peru's Cajamarca region is a rising star — altitude over 2,000 m and washed processing producing bright, clean cups.",
  "Papua New Guinea's Kainantu region produces coffees with wild, earthy character — often compared to aged Sumatra.",
  "Nicaragua's Jinotega department at 1,200–1,700 m gives silky-bodied washed coffees with mild stone-fruit notes.",
  "Honduras became Central America's top producer by volume in 2011, driven by altitude cooperatives in Copán and Marcala.",
  "Bolivia grows coffee at some of the world's highest elevations — the Caranavi region sits above 1,600 m.",
  "India's 'monsoon' processing exposes dried green beans to coastal winds for months, creating a unique musty sweetness.",
  "Indonesia's Flores island produces coffees distinct from Sumatra — brighter, with tropical fruit and spice notes.",
  "Tanzania's Kilimanjaro region coffees benefit from volcanic soil and altitude — often share Kenya's bright acidity.",
  "Mexico's Chiapas state produces most of the country's specialty coffee, grown by indigenous cooperatives above 1,500 m.",
  "El Salvador's Pacas variety is a natural mutation of Bourbon found only in this country.",

  // Processing
  "Natural (dry) processing: the whole cherry is dried on raised beds for 3–6 weeks before milling.",
  "Washed (wet) processing removes the fruit before drying — this highlights terroir and variety clarity.",
  "Honey processing is a hybrid: some mucilage remains on the bean. Yellow < Red < Black = more sweetness.",
  "Anaerobic fermentation happens in sealed tanks — CO₂ builds pressure, altering flavor dramatically.",
  "Extended fermentation is the driver behind 'winy' flavor notes — not the cherry itself.",
  "Thermal shock drying (rapid temp change) can stress the bean and reduce shelf life.",
  "Raised drying beds allow airflow under the coffee — ground drying raises contamination risk.",
  "Sorting after drying is critical: one fermented bean in a sack can taint an entire lot.",
  "The longer a coffee dries, the more sugars caramelize into the bean — up to a point.",
  "Double washed (Kenya AA style) involves two fermentation stages — explaining the intense fruit clarity.",
  "Carbonic maceration (CM) puts intact cherries into CO₂-filled tanks — adopted from winemaking, it amplifies sweetness.",
  "Turbo washed processing cuts fermentation with mechanical demucilaging — faster, cleaner, less complexity.",
  "Wet fermentation time matters: 12 hrs vs 48 hrs produces measurably different acidity profiles.",
  "Lacto-fermentation uses lactic acid bacteria to create structured, yogurt-like acidity in the final cup.",
  "Ethanol fermentation (wild yeast) produces the fruit-forward, boozy character in some naturals.",
  "SL28 and SL34 varieties were bred in Kenya for high yield and disease resistance — and happened to taste extraordinary.",
  "Peaberry beans form when only one seed develops per cherry — they are denser and roast more evenly.",
  "Freeze-drying instant coffee preserves more aromatics than spray-drying — the difference is measurable by GC-MS.",

  // Roasting
  "First crack is when water vapor and CO₂ escape the bean — the sound resembles popcorn.",
  "Second crack breaks down the bean's cell structure — most specialty roasters stop well before this.",
  "Light roast preserves the most origin character but demands precision brewing — low room for error.",
  "Roast date matters more than most brewing variables. Peak flavor window: 5–21 days post-roast for most methods.",
  "Degassing: freshly roasted coffee releases CO₂ for days. This is why immediate brewing often tastes flat.",
  "Development time ratio (DTR) — time after first crack as % of total roast — shapes sweetness vs. acidity.",
  "Dark roast hides origin character under roast flavor. The coffee's source matters much less.",
  "Nordic-style light roasts often taste 'sour' to those expecting darker profiles — it's extraction, not defect.",
  "Rate of Rise (RoR) is the rate at which bean temperature increases per minute — a flattening RoR often signals stalling.",
  "Maillard reactions (sugar + amino acids) develop most of a coffee's brown flavor compounds before first crack.",
  "Caramelization happens above 170°C and contributes sweetness, but also bitterness if pushed too far.",
  "Strecker degradation during roasting produces pyrazines — the 'nutty' and 'roasted' aroma precursors.",
  "Roast curve momentum matters: coasting into first crack at low heat can produce underdeveloped, 'baked' flavors.",
  "Scott Rao's work on RoR showed that a declining, never-flatlining curve produces the most even development.",
  "Charge temperature (the drum temp when green beans are loaded) sets the entire thermal trajectory of a roast.",
  "Drum speed affects bean agitation — higher RPM creates more even heat transfer and reduces tipping/scorching.",
  "Bean probe vs. air probe: air probe leads faster and reflects environment; bean probe lags and reflects actual bean temp.",
  "The 'crash and flick' RoR pattern (rapid drop then uptick near first crack) often indicates roaster technique issues.",
  "Endothermic vs. exothermic: drying phase is endothermic (absorbing heat); first crack releases heat exothermically.",
  "Tim Wendelboe roasts his coffees to a very light development — often under 15% DTR — aiming for maximum brightness.",

  // Water chemistry
  "Magnesium ions extract flavor compounds more efficiently than calcium — the key mineral for taste.",
  "Total Dissolved Solids (TDS) of 75–150 ppm is the SCA-recommended range for brewing water.",
  "Chlorine in tap water kills subtle aromatics. Even a small amount degrades specialty coffee.",
  "Distilled water produces flat, lifeless coffee — it needs some minerals to conduct extraction properly.",
  "Bicarbonate (KH) acts as a buffer, neutralizing acids — too much makes coffee taste flat and dull.",
  "Hard water forms limescale in kettles. A Brita + remineralizing approach preserves both equipment and taste.",
  "Championship water often targets 44–55 ppm — low enough for clarity, high enough for extraction.",
  "The SCA 'ideal' water recipe: 75–150 ppm TDS, magnesium ~10 ppm, bicarbonate ~40 ppm.",
  "Calcium enhances body and mouthfeel — a small amount (10–15 ppm) rounds out magnesium-forward recipes.",
  "Sodium ions can enhance sweetness perception at low levels — some competition recipes include 10–20 ppm sodium.",
  "The Third Wave Water capsule system is the easiest reproducible competition-water approach for home brewers.",
  "pH of 6.5–7.5 is the SCA-recommended range — outside this, extraction becomes uneven.",
  "Barometric pressure affects boiling point — at 2,000 m altitude, water boils at ~93°C instead of 100°C.",
  "RO (reverse osmosis) water removes everything — it then needs remineralizing to be useful for coffee.",
  "Chloramine (used in modern tap treatment) is harder to remove than chlorine — Brita filters don't fully remove it.",

  // Extraction science
  "Coffee is about 30% soluble — only 20–22% should end up in your cup for balanced extraction.",
  "Under-extracted coffee tastes sour and thin. Over-extracted tastes bitter and drying.",
  "The bloom (pre-infusion) allows CO₂ to escape, preventing uneven extraction channels.",
  "Grind size affects surface area: finer = more surface = faster extraction = risk of over-extraction.",
  "Water temperature affects extraction speed — lower temps can highlight acidity, higher temps extract more.",
  "Pour speed creates agitation — faster pours stir the bed, boosting extraction but risking channeling.",
  "Channeling occurs when water finds a path of least resistance through the coffee bed — rinse and reset.",
  "Turbulence during bloom helps saturate all grounds evenly — a gentle stir at 10 seconds is proven.",
  "Total brew yield weight (not just recipe volume) determines your actual TDS.",
  "A lower brew ratio (1:12) makes a stronger but not necessarily better cup — balance matters more.",
  "Brew ratio 1:15–1:17 is typical for filter coffee; 1:15 is stronger, 1:17 is lighter.",
  "Extraction yield % (EY) is the percentage of the dry coffee mass dissolved into the brew.",
  "A refractometer measures Brix (sugar content) and can be converted to TDS for precise extraction calculation.",
  "VST Coffee Tools created the industry standard for refractometer calibration in specialty coffee.",
  "Bypassing (adding hot water after brewing a concentrate) lets you hit higher extraction yields without bitterness.",
  "Grind distribution matters more than average grind size — a bimodal grind can cause simultaneous under/over-extraction.",
  "Fines in a grind accelerate extraction dramatically — even a few percent fines can shift flavor significantly.",
  "Leveling the coffee bed before pouring is crucial for even saturation — tilt, tap, or Weiss Distribution Technique.",
  "WDT (Weiss Distribution Technique) uses a thin needle to break up clumps before tamping or brewing.",
  "Percolation (water flowing through bed) vs. immersion (bed soaking) extract differently — immersion is more forgiving.",
  "Turbulence from a Drip Assist creates more even extraction than a hand pour for the same recipe.",
  "The 'sweet spot' on the extraction/strength matrix is where your palate finds balance — it varies by coffee.",

  // Equipment
  "The V60's large opening and angled ribs encourage fast, even drawdown — it rewards technique.",
  "Hario's 'Drip Assist' divides the pour into 8 slow streams — it mimics machine consistency.",
  "The Orea V4's modular base system changes flow rate dramatically — Apex bottom is the most restrictive.",
  "AeroPress uses pressure + immersion — it's the most forgiving brewer for imperfect grind or water.",
  "AeroPress inverted method eliminates dripping during steep — same result, more control.",
  "The Clever Dripper combines immersion steep with a V60-style filter — James Hoffmann's method is definitive.",
  "Kalita Wave's flat bed and three holes promote even extraction — it's more forgiving than V60.",
  "Moccamaster's gold standard: fixed 92–96°C water, 6-minute brew cycle, SCAA certified.",
  "The Niche Zero is a zero-retention conical grinder — what you grind in comes out, instantly.",
  "Comandante C40 uses high-nitrogen hardened steel burrs — remarkably consistent for a hand grinder.",
  "Fellow Corvo EKG's PID holds temperature within ±0.5°C — critical for washed high-acidity coffees.",
  "Scale precision matters: 0.1g resolution is important for espresso; 1g is fine for pour-over.",
  "The Orea V3 plastic body retains heat better than ceramic or glass — important for small doses.",
  "Hario V60 ceramic retains heat better than plastic — relevant for longer brews or cold kitchens.",
  "The Fellow Stagg kettle's counterbalanced spout gives unusually fine pour control for a gooseneck.",
  "Pulse pouring vs. continuous pour: pulse gives more agitation and extraction, continuous is more consistent.",
  "Metal (stainless, gold) filters allow oils and micro-fines through — fuller body, less clarity than paper.",
  "Cloth (flannel) filters produce the cleanest cup after paper — almost no oils pass, but cleaning is demanding.",
  "The 1Zpresso JX-Pro and K-Max are considered the best value hand grinders for filter by most enthusiasts.",
  "Weber Workshops EG-1 is a single-dose flat burr grinder — often cited as the reference standard for filter.",
  "Flat burrs tend toward bimodal distribution; conical burrs produce a single-peak distribution.",
  "Burr alignment matters far more than burr material — a misaligned burr of any quality produces uneven grinds.",
  "The Niche Zero's conical burrs produce a 'sweet' extraction profile — slightly more body than flat-burr references.",
  "The Comandante Red Clix upgrade narrows the click interval from ~40 to ~90 per rotation — finer adjustment.",
  "Flow restrictors (like Pulsar's variable bottom) let you dial drawdown speed independently of grind size.",

  // Brew methods deep-dives
  "Tetsu Kasuya's 4:6 Method separates flavor from strength — the first 40% controls acidity/sweetness.",
  "The 4:6 Method's genius: you can adjust two variables independently without changing dose or ratio.",
  "Peng Jiajun's 2025 WBC recipe uses temperature staging — 96°C bloom, then 80°C final pour.",
  "Temperature staging reduces late-extraction bitterness while preserving early bloom aromatics.",
  "James Hoffmann's V60 technique: one continuous pour after bloom — simplicity enables consistency.",
  "Tim Wendelboe's method uses a relatively coarse grind and high temp — maximizing clarity and brightness.",
  "The 'rao allonge' is a high-ratio (1:8+) espresso variant used as a base for pour-over-like clarity.",
  "Cold brew uses time instead of heat — extraction happens over 12–24 hours at room temperature.",
  "Flash-chilled iced coffee (hot brew over ice) preserves acidity and aromatics better than cold brew.",
  "Japanese iced coffee (hot bloom + brew over ice) is a classic specialty café method — aromatics are notably bright.",
  "The Orea 'V60-style' two-pour method: bloom then a single long pour to target — clean and high clarity.",
  "Lance Hedrick's competition recipes consistently target the highest EY possible without crossing into astringency.",
  "Hugh Kelly's 2023 WBC routine used temperature profiling to highlight specific terpene compounds in his coffee.",
  "An 'Allongé' pull in espresso achieves filter-like sweetness and acidity at about 1:6–1:8 ratio.",
  "The AeroPress World Championship (AWAC) produces hundreds of creative recipes annually — freely available online.",
  "Scott Rao's 'percolation recipe' uses a 3:1 water-to-coffee bloom followed by a steady continuous pour.",
  "Split-brewing (two brewers, blend after) lets you target different parameters for different cups from one dose.",
  "Pre-wetting the filter AND the brewer body is especially important in cold environments — heat loss is significant.",
  "Slow-drip ice drip coffee (Kyoto style) brews at 1 drop per second over 8–12 hours — intensely aromatic.",

  // Sensory & tasting
  "The Specialty Coffee Association flavor wheel has 110 flavor descriptors across 9 categories.",
  "Retronasal olfaction (aromatics reaching your nose while drinking) drives 80%+ of flavor perception.",
  "Brightness and acidity are often the same thing — perceived differently depending on context and culture.",
  "Body is determined by the oils and fine particles remaining in the cup — metal filters allow more through.",
  "Sweetness in coffee isn't added sugar — it's sucrose and other compounds surviving the roast.",
  "A 'clean cup' in SCA terms means no flavor defects — it's a quality baseline, not a style preference.",
  "Bitterness isn't inherently bad — caffeine and chlorogenic acids in balance add depth and length.",
  "'Finish' or 'aftertaste' duration indicates coffee quality — longer pleasant finish = better extraction.",
  "Cupping protocol uses 93°C water, 8.25g per 150ml, 4-minute steep — standardized for fair comparison.",
  "A cupping score of 80+ qualifies as 'specialty grade' by SCA standards.",
  "Phosphoric acid (naturally in some Kenyan coffees) gives a clean, almost carbonated brightness.",
  "Malic acid (found in apples) creates a rounded, soft acidity — typical of washed Central Americans.",
  "Citric acid produces a sharp, lemon-like brightness — prominent in Ethiopian washed coffees.",
  "Tartaric acid (common in wine) appears in some naturals and processed coffees — adds complexity.",
  "Lactic acid (yogurt, milk) is produced during controlled fermentation — adds a soft, creamy texture.",
  "Succinic acid contributes savory, wine-like depth — often a positive note in complex washed lots.",
  "Astringency is a tactile sensation (drying, gripping), not a flavor — caused by polyphenols binding proteins.",
  "Mouthfeel (viscosity, coating) is distinct from body — both matter but are perceived differently.",
  "The SCA cupping form scores 10 attributes: fragrance, aroma, flavor, aftertaste, acidity, body, balance, uniformity, cleanliness, sweetness.",
  "'Terroir' in coffee encompasses soil, altitude, rainfall, temperature variation, and shade — all measurable influences.",
  "Cup of Excellence (COE) auctions identify the top lots from each country — scores 87+ are considered extraordinary.",
  "A 90+ COE score can fetch $100+ per pound green — the economics of micro-lot coffee in full effect.",
  "Blind cupping reveals bias: the same coffee tasted before and after knowing its origin scores differently.",

  // Variety science
  "Arabica (C. arabica) contains ~1.2% caffeine; Robusta (C. canephora) contains ~2.7% — nearly double.",
  "All Arabica cultivars trace back to Ethiopia's wild forests — the genetic diversity there is irreplaceable.",
  "Typica is one of the oldest known cultivars — it spread from Yemen to the Americas in the 1700s.",
  "Bourbon variety split from Typica on Réunion Island (formerly Bourbon) — slightly higher yield and sweetness.",
  "Caturra is a Bourbon mutation from Brazil — compact, high-yield, but cup quality is considered slightly lesser.",
  "Catuai is a cross of Mundo Novo and Caturra — bred for disease resistance, widely grown in Brazil and Honduras.",
  "SL28 was selected from a Kenyan drought-resistant variety — its intense blackcurrant note is genetically expressed.",
  "Pacamara is a cross of Pacas (El Salvador) and Maragogipe — large bean, complex, often tea-like with fruit.",
  "Maragogipe is a Typica mutation producing giant beans — often called 'elephant bean', low yield but curious cup.",
  "Laurina (Bourbon Pointu) is a naturally low-caffeine Bourbon mutation — extremely rare, delicate, and expensive.",
  "Pink Bourbon is a Colombian landrace possibly related to both Yellow and Red Bourbon — noted for stone-fruit clarity.",
  "Ethiopian Heirloom refers to the thousands of unnamed wild varieties growing in Ethiopia — huge genetic diversity.",
  "F1 hybrids (cross of Timor hybrid x Arabica) offer disease resistance + quality — Centroamericano is one example.",
  "Timor hybrid is a natural cross of Arabica and Robusta — disease resistant but carries some Robusta character.",
  "Gesha variety produces the highest scoring coffees at auction year after year — extraordinary floral, tea-like character.",
  "The 2004 Best of Panama auction changed specialty coffee history — Hacienda La Esmeralda's Gesha scored 95.9.",
  "Sidra is a unique Colombian variety with intense aromatics — possibly a hybrid of Ethiopian Heirloom × Typica.",
  "Wush Wush is a rare Ethiopian wild variety — gaining attention for extreme floral complexity and jasmine notes.",
  "Eugenioides (C. eugenioides) is a parent species of Arabica — a rare, low-caffeine coffee with honey-sweet character.",
  "Variety matters as much as processing — the same process on Gesha vs. Caturra produces vastly different cups.",

  // History & culture
  "Coffee was first consumed as a food in Ethiopia — the beans were mixed with animal fat for energy.",
  "The first European coffeehouse opened in Oxford in 1650. They were called 'penny universities'.",
  "The French press was patented in 1929 by Milanese designer Attilio Calimani.",
  "Espresso machines use pressure, not high heat — the goal is 9 bar, not boiling water.",
  "The Vienna Philharmonic gift shop reportedly inspired James Hoffmann to enter the coffee world.",
  "World Barista Championship was first held in Monte Carlo in 2000. The format: 4 espresso, 4 milk, 4 signature.",
  "Blue Bottle Coffee (founded 2002) pioneered the third-wave model of transparent sourcing in the US.",
  "Specialty coffee's 'third wave' began as a consumer movement caring about origin, process, and roaster craft.",
  "Stumptown, Intelligentsia, and Counter Culture were instrumental in bringing direct-trade sourcing to scale.",
  "The coffee cherry is actually a fruit — each cherry typically contains two beans (seeds) facing each other.",
  "Arabia Felix ('happy Arabia') was medieval Europe's name for Yemen — the only known source of coffee for centuries.",
  "The Ottoman Empire spread coffeehouses across the Middle East in the 16th century — they were centers of debate.",
  "Coffee was banned multiple times by various rulers — it was seen as too stimulating and politically dangerous.",
  "Luigi Bezzera filed the first espresso machine patent in 1901 — Desiderio Pavoni commercialized it.",
  "The La Marzocco brand (founded 1927) made the first espresso machine with separate boilers for steam and brew.",
  "The 1961 Faema E61 was the first commercial espresso machine with motor-pump pressure — still referenced today.",
  "Freeze-dried Nescafé was launched in 1938 — it fed Allied soldiers in WWII and changed how the world drank coffee.",
  "The SCA was formed in 2017 from the merger of the SCAA (American) and SCAE (European) associations.",
  "Coffee is the second most traded commodity in the world after crude oil.",
  "Café de Colombia's Juan Valdez marketing campaign (1958) was so successful it transformed the entire country's image.",

  // Roasters & producers
  "April Coffee (Copenhagen) is James Hoffmann's roastery — focused on maximum transparency and reproducible recipes.",
  "Tim Wendelboe (Oslo) is one of the most influential specialty roasters in the world — 2004 World Barista Champion.",
  "Onyx Coffee Lab (Bentonville, Arkansas) pioneered the 'cold-hold bloom' technique and publishes recipes openly.",
  "Square Mile Coffee (London) was co-founded by James Hoffmann and Anette Moldvaer — driven by sensory research.",
  "Heart Coffee (Portland) and Stumptown shaped the early US third wave.",
  "Koppi (Helsingborg, Sweden) is a leading Nordic specialty roaster with a strong focus on process diversity.",
  "Nomad Coffee (Barcelona) is an influential Spanish specialty roaster known for consistent light-roast quality.",
  "Go Brew (Seoul) is one of the most celebrated specialty roasters in the rapidly growing Korean specialty scene.",
  "Fuglen (Tokyo + Oslo) bridges Scandinavian and Japanese coffee culture with shared sourcing and philosophy.",
  "Five Elephant (Berlin) trained baristas who founded some of Germany's best specialty cafés.",
  "Georg (Vienna) is a reference Austrian specialty roaster — clean, transparent, and competition-focused.",
  "The Barn (Berlin) is one of the oldest European third-wave roasters — still pushing process innovation.",
  "Coffee Collective (Copenhagen) publishes full traceability data including farmer payment — a transparency leader.",
  "Hacienda La Esmeralda (Panama) holds multiple world auction records for its Gesha lots.",
  "Ninety Plus Coffee pioneered ultra-controlled fermentation techniques — Kemgin and Perci changed what was possible.",

  // Championships & experts
  "The 2023 World Barista Champion was Boram Um from South Korea — her routine featured a highly complex signature.",
  "The 2024 WBC was won by Sasa Sestic — his second win, unprecedented in WBC history.",
  "Matt Perger (2012 WBC) is known for advocating grind distribution over grind fineness.",
  "Erna Knutsen coined the term 'specialty coffee' in 1974 — she meant: 'special geographic microclimates.'",
  "Klaus Thomsen won the 2006 WBC using a pour-over as a signature drink — almost unheard of then.",
  "Scott Rao's 'The Coffee Roaster's Companion' (2014) remains the definitive reference text for specialty roasting.",
  "James Hoffmann's YouTube channel has educated millions on specialty coffee technique — Guinness record-level reach.",
  "Lance Hedrick is known for pushing extraction yield limits — testing 24%+ EY on filter with carefully sorted grinds.",
  "Sasa Sestic's 2015 WBC win introduced carbonic maceration processing to a global audience.",
  "The AeroPress Championship format uses a 'play-off' style — any recipe is allowed, judged blindly.",
  "World Brewers Cup (WBrC) tests filter coffee — competitors prepare and serve one bar-choice and one open-choice coffee.",
  "The WBrC technical service score is judged on procedure; the sensory score is blind.",
  "Tetsu Kasuya won the 2016 WBrC with his 4:6 method — it's now taught worldwide.",
  "Charles Babinski (2015 WBC runner-up) invented the 'lentil pour' — fast first pour to create turbulence.",

  // Practical tips
  "Freezing whole beans in an airtight bag and grinding from frozen is a proven way to extend peak freshness.",
  "Coffee goes stale from oxygen, moisture, light, and heat — in that order of impact.",
  "Storing coffee in its original bag (with one-way valve) in a cool, dark cupboard works well for 2–3 weeks.",
  "A one-way valve lets CO₂ out but keeps oxygen from entering — essential for fresh-roast packaging.",
  "Pre-wetting your paper filter removes papery taste and preheats your brewer.",
  "Weighing water instead of measuring by volume accounts for density and temperature variance.",
  "Your kettle cools roughly 1°C every 30 seconds in open air — track this for multi-pour recipes.",
  "The Niche Zero's grind retention of <0.1g means virtually no old grounds mixed into your dose.",
  "Lightly tapping the portafilter or brewer mid-pour can help reset a channeling bed.",
  "If your V60 drains too fast, check grind size first — then look at bloom technique and pour rate.",
  "Rinsing paper filters with the hottest water you have removes more fines and paper taste.",
  "Pour in concentric circles to ensure even saturation — avoid pouring directly on the filter walls.",
  "The water level during bloom should just cover the grounds — too much water negates the CO₂ release.",
  "Let the kettle sit at temperature for 30 seconds before pouring — temperature gradients in the spout even out.",
  "Cupping at home is the fastest way to taste the same coffee under different variables side-by-side.",
  "Taste your brew water on its own first — if it tastes off, your coffee will taste off.",
  "Clean grinder burrs every 200–300g of coffee — stale oils transfer directly into the cup.",
  "The Hario V60 filter 'wedge fold' creates a more secure seal against the dripper walls.",
  "Transferring brewed coffee to a preheated thermos (not back on heat) preserves flavor for 30+ minutes.",
  "Slow pours from a gooseneck improve flow control — hold the kettle handle at its balance point.",
  "Whole beans stay fresh 3–6 months in an airtight container; ground coffee stales within 30 minutes.",
  "The 'Swiss water' decaf process uses no chemicals — water and carbon filters do all the work.",
  "Mountain Water Process (Mexico) and CO₂ decaf are the two most flavor-preserving decaffeination methods.",
  "A simple trick to test stale beans: bloom them and watch for no bubbles — stale beans barely degas.",
  "Cupping spoons should be pre-heated in hot water to avoid thermal shock to the sample.",
  "If your grinder clogs mid-dose, the beans are too oily (dark roast) or too fresh — both cause sticking.",

  // Science & chemistry
  "Coffee contains over 1,000 aroma compounds — wine contains around 600.",
  "Caffeine is a natural pesticide produced by the coffee plant — it deters insects feeding on the leaves.",
  "Chlorogenic acids (CGAs) are the dominant polyphenols in green coffee — they degrade during roasting.",
  "CGAs contribute to the perceived bitterness and astringency of dark roasts.",
  "Trigonelline, an alkaloid in coffee, is a precursor to vitamin B₃ (niacin) — it degrades into niacin during roasting.",
  "Acrylamide forms in coffee during roasting (Maillard reaction at high temps) — lighter roasts contain less.",
  "Furans are the dominant roast-derived aroma compounds — they contribute 'caramel' and 'nutty' character.",
  "Pyrazines form from Strecker degradation — they add 'earthy', 'nutty', and 'roasted' aromas.",
  "Coffee lipids (waxes, oils) carry fat-soluble aroma compounds — paper filters largely remove them.",
  "Caffeine is more soluble at higher temperatures — hot brew extracts more caffeine than cold brew.",
  "Cold brew has lower titratable acidity despite similar caffeine — the acids are simply less extracted.",
  "The Maillard reaction in coffee starts around 150°C — much lower than traditionally taught (154°C+ in food science).",
  "CO₂ solubility in water decreases as temperature rises — this is why bloom is so much more active with hot water.",
  "Coffee bean density correlates with altitude: higher grown = denser = more complex flavor precursors.",
  "Green coffee moisture content at export should be 10–12% — above 12% risks mold; below 8%, the bean is brittle.",
  "The SCA green coffee grading system allows 0 primary defects and max 5 full defects per 350g sample.",

  // Climate, sustainability, and future
  "Climate change is shifting optimal growing altitudes upward — many farms are replanting at higher elevations.",
  "Leaf rust (Hemileia vastatrix) devastated Central American crops in 2012 — driving variety research intensively.",
  "Shade-grown coffee produces lower yields but higher cup quality, and supports biodiversity vs. sun cultivation.",
  "Direct trade (roaster ↔ farmer) can return 2–3× more to the producer than commodity-chain FairTrade.",
  "Regenerative agriculture in coffee farming — composting, cover crops, polyculture — is gaining traction globally.",
  "By 2050, climate models suggest 50% of current coffee-growing regions will be unsuitable — 'climate-smart' varieties are critical.",
  "Coffee traceability tools (GPS lot mapping, QR-code sourcing) are now common among leading specialty roasters.",
  "Certifications: Rainforest Alliance, Fair Trade, and Organic all measure different things — none guarantees cup quality.",
  "Cascara (dried coffee cherry tea) has been drunk in Yemen and Bolivia for centuries — now trending in specialty cafés.",
  "Specialty coffee's 'fourth wave' focuses on radical transparency: producer payment, carbon footprint, water use per kg.",
];

/** Returns a shuffled subset of hints for a single loading session */
export function getLoadingHints(count = 6): string[] {
  const shuffled = [...COFFEE_HINTS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
