-- 0013 — Insights (multivariate coach memory)
--
-- The lessons table (0012) writes one row per (level, scope) tuple, with
-- each scope seeing only its own brews. That single-axis aggregation
-- structurally cannot produce multivariate observations like "low dose ×
-- delicate Pink Bourbons × peak freshness → higher scores" — the
-- observation lives across dose × variety × process × rating
-- simultaneously, but lessons indexes by ONE axis.
--
-- Insights is the multivariate-friendly replacement. One row = one
-- coach observation generated by Opus over the full session corpus,
-- with the dormant analysis pipeline (extractor + patterns +
-- brewSignature) feeding multi-axis structured input. Each row carries:
--   - observation: one sentence citing real counts ("19 of 28 washed
--     brews scored 4★+ when in peak freshness; 3 of 9 past-peak")
--   - suggestion: one sentence (next action or open question)
--   - citation_fields: the fields the observation cites, for downstream
--     filtering (e.g. /recommend ranks an insight higher when the
--     current brew's variety/process matches)
--   - latest_session_ms: the session corpus the insight was computed
--     against; future insights pages skip regeneration if this hasn't
--     advanced (lightweight cache key)
--
-- The user-status fields (dismissed_at, user_note) let the user thumb
-- down an insight; /recommend respects dismissals.
--
-- Run with:
--   cat src/lib/db/migrations/0013_add_insights.sql | docker compose exec -T postgres psql -U brewlog -d brewlog

CREATE TABLE IF NOT EXISTS insights (
  id                  text PRIMARY KEY,
  observation         text NOT NULL,
  suggestion          text NOT NULL,
  citation_fields     jsonb NOT NULL DEFAULT '[]'::jsonb,
  latest_session_ms   bigint NOT NULL,
  source              text NOT NULL DEFAULT 'opus' CHECK (source IN ('opus', 'user-confirmed')),
  dismissed_at        timestamptz,
  user_note           text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS insights_latest_session_ms_idx ON insights (latest_session_ms DESC);
CREATE INDEX IF NOT EXISTS insights_dismissed_at_idx ON insights (dismissed_at);
CREATE INDEX IF NOT EXISTS insights_created_at_idx ON insights (created_at DESC);
