import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { requireAuth } from "@/lib/auth/requireAuth";

export const dynamic = "force-dynamic";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

function stripHtml(str: string): string {
  return str
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function sanitizeProfile(obj: Record<string, unknown>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === "string") {
      result[key] = stripHtml(value);
    } else if (Array.isArray(value)) {
      result[key] = value.map(item => typeof item === "string" ? stripHtml(item) : item);
    } else {
      result[key] = value;
    }
  }
  return result;
}

export async function POST(req: NextRequest) {
  const authError = await requireAuth(req);
  if (authError) return authError;

  try {
    const { name }: { name: string } = await req.json();
    if (!name) return NextResponse.json({ error: "name required" }, { status: 400 });

    const prompt = `Search the web for the specialty coffee roaster "${name}". Find their actual location (city and country), what they are known for, and their roasting philosophy or approach.

After searching, return ONLY valid JSON — no markdown, no explanation:
{
  "name": "${name}",
  "region": "city and country from search results, e.g. Amsterdam, Netherlands — null if not found",
  "styleSummary": "2 sentences from real search results: (1) where they are based and what makes them special or famous; (2) how they roast and what cup profiles they aim for",
  "roastTendency": "very-light" | "light" | "light-medium" | "medium" | "varied",
  "solubilityBias": "high" | "moderate" | "low" | "varied",
  "clarityVsSweetnessBias": "clarity" | "sweetness" | "balanced" | "varied",
  "agitationTolerance": "sensitive" | "moderate" | "robust",
  "tempBias": "high" | "standard" | "low",
  "ratioBias": "lean" | "standard" | "rich",
  "methodAffinities": ["V60", "..."],
  "extractionRisks": ["..."],
  "notes": "1-2 sentences on best brewing approach",
  "confidence": "inferred",
  "disclaimer": "Profile generated by AI. Verify against the bag and your own brew results."
}

Use only information from search results for region and styleSummary. Do not invent location data.`;

    // Use beta.messages with web_search server tool — Anthropic executes the search
    const response = await client.beta.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 1024,
      tools: [{ type: "web_search_20250305", name: "web_search" }],
      messages: [{ role: "user", content: prompt }],
      betas: ["web-search-2025-03-05"],
    });

    // Extract text blocks from response (server tool results are embedded; stop_reason is end_turn)
    console.log("roasters/generate content types:", response.content.map(b => b.type).join(", "));
    const texts: string[] = [];
    for (const block of response.content) {
      if (block.type === "text") {
        texts.push(block.text);
      }
    }
    const text = texts.join("");
    console.log("roasters/generate text:", text.slice(0, 300));

    const match = text.match(/\{[\s\S]*\}/);
    if (!match) throw new Error("No JSON in response");
    const prior = sanitizeProfile(JSON.parse(match[0]) as Record<string, unknown>);
    return NextResponse.json(prior);
  } catch (err) {
    console.error("roasters/generate error:", err);
    return NextResponse.json({ error: "Generation failed" }, { status: 500 });
  }
}
