#!/usr/bin/env node
/**
 * Vercel Deployment Source Recovery Script
 *
 * Downloads all source files from a specific Vercel deployment and saves them
 * locally. Run this on a machine that can reach api.vercel.com.
 *
 * Usage:
 *   node scripts/recover-vercel.mjs
 *
 * Output:
 *   ./vercel-recovery/   ← complete source tree from the deployment
 *   ./vercel-diff.txt    ← list of files that differ from the local repo
 */

import { mkdir, writeFile, readFile } from 'fs/promises';
import { existsSync, createWriteStream } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// ─── Config ──────────────────────────────────────────────────────────────────
const TOKEN = process.env.VERCEL_TOKEN;
if (!TOKEN) {
  console.error('Error: VERCEL_TOKEN environment variable is required.');
  console.error('  export VERCEL_TOKEN=<your-token>  # then re-run');
  process.exit(1);
}
const DEPLOYMENT_ID = '82RzzAfVC';
const OUTPUT_DIR = path.resolve('./vercel-recovery');
const DIFF_LOG = path.resolve('./vercel-diff.txt');

// Skip binary / generated files we don't need to recover
const SKIP_PATTERNS = [
  /^\.next\//,
  /^node_modules\//,
  /\.tsbuildinfo$/,
  /package-lock\.json$/,  // will be regenerated by npm install
];

// ─── Helpers ─────────────────────────────────────────────────────────────────
const BASE_URL = 'https://api.vercel.com';

async function apiGet(url, binary = false) {
  const res = await fetch(`${BASE_URL}${url}`, {
    headers: { Authorization: `Bearer ${TOKEN}` },
  });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Vercel API ${res.status} for ${url}: ${body}`);
  }
  return binary ? res.arrayBuffer() : res.json();
}

/**
 * Recursively collect { path, uid } for every file in the deployment tree.
 */
function collectFiles(nodes, prefix = '') {
  const files = [];
  for (const node of nodes) {
    const fullPath = prefix ? `${prefix}/${node.name}` : node.name;
    if (node.type === 'directory' && Array.isArray(node.children)) {
      files.push(...collectFiles(node.children, fullPath));
    } else if (node.type === 'file' && node.uid) {
      files.push({ path: fullPath, uid: node.uid });
    }
  }
  return files;
}

function shouldSkip(filePath) {
  return SKIP_PATTERNS.some((re) => re.test(filePath));
}

async function ensureDir(dir) {
  if (!existsSync(dir)) await mkdir(dir, { recursive: true });
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log(`\n🔍  Fetching file tree for deployment ${DEPLOYMENT_ID}…`);
  const tree = await apiGet(`/v6/deployments/${DEPLOYMENT_ID}/files`);
  const allFiles = collectFiles(tree);
  const files = allFiles.filter((f) => !shouldSkip(f.path));

  console.log(`📁  Found ${allFiles.length} files total, downloading ${files.length} (skipping ${allFiles.length - files.length} generated/binary).\n`);

  const diffLines = [];
  let downloaded = 0;
  let skippedIdentical = 0;
  let errors = 0;

  for (const { path: filePath, uid } of files) {
    const outPath = path.join(OUTPUT_DIR, filePath);
    const localPath = path.resolve(filePath); // compare against local repo root

    try {
      // Download content
      const buffer = await apiGet(`/v7/deployments/${DEPLOYMENT_ID}/files/${uid}`, true);
      const vercelContent = Buffer.from(buffer);

      // Compare with local file if it exists
      let isDiff = true;
      if (existsSync(localPath)) {
        const localContent = await readFile(localPath);
        isDiff = !localContent.equals(vercelContent);
      } else {
        diffLines.push(`NEW: ${filePath}`);
      }

      if (isDiff) {
        // Save to output directory
        await ensureDir(path.dirname(outPath));
        await writeFile(outPath, vercelContent);
        console.log(`  ✅  ${filePath}`);
        if (existsSync(localPath)) diffLines.push(`CHANGED: ${filePath}`);
        downloaded++;
      } else {
        skippedIdentical++;
      }
    } catch (err) {
      console.error(`  ❌  ${filePath}: ${err.message}`);
      diffLines.push(`ERROR: ${filePath} — ${err.message}`);
      errors++;
    }
  }

  // Write diff log
  if (diffLines.length > 0) {
    await writeFile(DIFF_LOG, diffLines.join('\n') + '\n');
  }

  console.log(`
────────────────────────────────────────
Recovery complete.

  Downloaded (changed/new): ${downloaded}
  Identical to local:        ${skippedIdentical}
  Errors:                    ${errors}

Changed files written to:   ${OUTPUT_DIR}
Diff summary:               ${DIFF_LOG}

Next step:
  Copy changed files from vercel-recovery/ back into the repo root,
  then run:  git add -A && git commit -m "recover: restore April 11 Vercel deployment"
             git push -u origin claude/recover-brewlog-vercel-y5LUx
────────────────────────────────────────
`);
}

main().catch((err) => {
  console.error('\nFatal:', err.message);
  process.exit(1);
});
